
package br.com.soc.exame.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExameWSService", targetNamespace = "http://ws.exame.soc.com.br/", wsdlLocation = "file:/Users/fabricoliveira/workspace-age_technology/exameweb/src/main/java/ExameWS.wsdl")
public class ExameWSService
    extends Service
{

    private final static URL EXAMEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXAMEWSSERVICE_EXCEPTION;
    private final static QName EXAMEWSSERVICE_QNAME = new QName("http://ws.exame.soc.com.br/", "ExameWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/fabricoliveira/workspace-age_technology/exameweb/src/main/java/ExameWS.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMEWSSERVICE_WSDL_LOCATION = url;
        EXAMEWSSERVICE_EXCEPTION = e;
    }

    public ExameWSService() {
        super(__getWsdlLocation(), EXAMEWSSERVICE_QNAME);
    }

    public ExameWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMEWSSERVICE_QNAME, features);
    }

    public ExameWSService(URL wsdlLocation) {
        super(wsdlLocation, EXAMEWSSERVICE_QNAME);
    }

    public ExameWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMEWSSERVICE_QNAME, features);
    }

    public ExameWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExameWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExameWS
     */
    @WebEndpoint(name = "ExameWS")
    public ExameWS getExameWS() {
        return super.getPort(new QName("http://ws.exame.soc.com.br/", "ExameWS"), ExameWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExameWS
     */
    @WebEndpoint(name = "ExameWS")
    public ExameWS getExameWS(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.exame.soc.com.br/", "ExameWS"), ExameWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMEWSSERVICE_EXCEPTION!= null) {
            throw EXAMEWSSERVICE_EXCEPTION;
        }
        return EXAMEWSSERVICE_WSDL_LOCATION;
    }

}
